name: Update Data From LFX
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jmertic/lfx-tac-actions@main
        with:
          updateprojects: false
          updatetacmembers: false
          updatetacagendaitems: false
          updateclomonitor: false
          updatedecks: true
          updatecharters: true
          slug: open-mainframe-project
          overview_decks: '[{"url": "https://docs.google.com/presentation/d/1Zk3REYGnE6mYIXl52QxzNbVW7XM2NPs_1w7YxscRXrk/edit?usp=sharing","filename": "Open Mainframe Project - Overview"},{"url":"https://docs.google.com/presentation/d/1x8f47QPzhuIP9LM9QthYih8VoJhJvPAAXoy6nW0uF6c/edit?usp=sharing","filename": "Open Mainframe Project - Governing Board Overview"},{"url":"https://docs.google.com/presentation/d/18l_SwTF3LOEzoYyi0fMX-Wve2GIZb1cLQswJCZEjN9M/edit?usp=sharing","filename": "Open Mainframe Project - TAC Overview"},{"url":"https://docs.google.com/presentation/d/1SW-JbXTQgwb_OczGeyo5jqc6GmK5CLmBTzg0pb0vMXs/edit?usp=sharing","filename":"Open Mainframe Project - Membership Overview"}]'
        env:
          token: ${{ secrets.PAT }} 
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
